### ISSUE TITLE
Bug in mapdamagegeomparam script: `AttributeError: 'DataFrame' object has no attribute 'ix'`

### ISSUE THREAD

**Issue by jfy133** [mlell/tapas#1]
# Bug

I was trying out tapas and came across the following bug, when running the following I would get the error:

```
❯ $TAPAS/mapdamagegeomparam --fit-plots fig/fit.png input/mapdamage/misincorporation.txt
Traceback (most recent call last):
  File "/raven/u/jfellowsy/bin/tapas-1.2/scripts/src/mapdamage2geomparam.py", line 436, in <module>
    if __name__=="__main__": main()
  File "/raven/u/jfellowsy/bin/tapas-1.2/scripts/src/mapdamage2geomparam.py", line 68, in main
    A = A.ix[A.Total != 0,:]
  File "/u/jfellowsy/conda-envs/tapas/lib/python3.9/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

```
This is derived from this line:

https://github.com/mlell/tapas/blob/6d7e2739b986592e97e19d0af1aca7eb1b1a8fe3/scripts/src/mapdamage2geomparam.py#L68

Where the `ix` column  doesn't exist in the input mapDamage2 misincorporation file. 

# Workaround

Delete the referred to line in the above script, that refers to `ix` (assuming your misincorporation file doesn't have any 0s).

I was then successfully able to get the script ot run prpoerly.

**Comment by mlell** [comment]
Hi, 
on new versions of the pandas package `DataFrame.ix` seems to have been replaced by `.loc`. Thanks for this, I'll look into it
https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix

**Comment by jfy133** [comment]
Ah that could be the issue. I tried to install all the dependencies with exact versions via bioconda (for reproducibility) but unfortuanately I couldn't this to work due to conflicts or versions that are too old for bioconda. 

I've therefore 'blindly' installed the latest versions of everything and somewhat hoping for the best.

```
conda create -n tapas -c bioconda python=3 r-essentials=4.0 r-base=4.0.3 bwa=0.7.17 bowtie2=2.4.2 minimap2=2.18 hisat2=2.2.1
```

Could be the pandas version I installed therefore wasn't compatible.
